### ISSUE TITLE
裁片数量变多后效果就变差了？

### ISSUE THREAD

**Issue by balcklive** [klaoli/2D_Irregular_Packing#1]
[ntx.txt](https://github.com/user-attachments/files/17932116/ntx.txt)
可以试试这个数据集

**Comment by klaoli** [comment]
裁片数量<40时，算法效果还可以。裁片数量越多，解空间片数量越多，解越大，越不容易找到较优解(对于几百个零件的排样，代码中的算法已不再适用)。ntx.txt文件里的裁片顶点数太多，导致过多几何计算，可以简化多边形，再来执行算法

**Comment by balcklive** [comment]
好的，这个算法后续还会再更新吗？持续关注

**Comment by klaoli** [comment]
会更新，最近几天更新下代码，使用您提供的数据集测试下

**Comment by klaoli** [comment]
使用ntx.txt测试，对数据集中的多边形进行简化后，利用率84%

**Comment by balcklive** [comment]
获得84%的利用率用了多长时间呢？

**Comment by klaoli** [comment]
10分钟左右吧

**Comment by klaoli** [comment]
算法执行30分钟，ntx最好结果达到86%
![ntx](https://github.com/user-attachments/assets/53b6dbcc-573f-4b1c-8e40-329807e78e1f)
